#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install nginx -y

# Create the server block file
sudo nano /etc/nginx/sites-available/redirect_me

# Paste the server block configuration into the file
cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    server_name youtube.com;

    location /redirect_me {
        return 301 https://https://www.youtube.com/watch?v=ZxKM3DCV2kE&list=WL;
    }
}
EOF

# Create a symbolic link to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test the configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo systemctl reload nginx
