#!/usr/bin/env bash
# starts nginx as nginx user, listenson all active IPs on port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"
